roll=int(input("enter student number:"))
name=input("enter student name:")
p = float(input("enter marks in physics:"))
c = float(input("enter marks in chemistry:"))
m = float(input("enter marks in maths:"))
total = round(p+c+m,2)
avg=round(total/3,2)
print("student details:")
print("Student Number :",roll)
print("physics marks:",p)
print("chemistry marks:",c)
print("maths marks:",m)
print("Student Name :",name)
print("Total Marks :",total)
print("Average Marks :",avg)